<?php

declare(strict_types=1);

namespace App\Core\Console\Commands;

use App\Core\Registry\ModuleRegistry;
use Illuminate\Console\Command;

class ModuleCacheCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'module:cache';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Compile and cache module manifests, routes, configs, and permissions';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('Compiling modules configuration...');

        $cache = [
            'modules' => [],
            'providers' => [],
            'routes' => [],
            'configs' => [],
            'permissions' => [],
            'events' => [],
            'listeners' => [],
            'policies' => [],
            'migrations' => [],
            'seeders' => [],
        ];

        foreach (ModuleRegistry::getModules() as $moduleClass) {
            $path = ModuleRegistry::getModulePath($moduleClass);
            $manifestPath = $path . '/module.json';

            if (!file_exists($manifestPath)) {
                continue;
            }

            $manifest = json_decode((string) file_get_contents($manifestPath), true);
            $name = $manifest['name'] ?? class_basename($moduleClass);

            $cache['modules'][$name] = [
                'class' => $moduleClass,
                'path' => $path,
                'version' => $manifest['version'] ?? '1.0.0',
                'enabled' => $manifest['enabled'] ?? true,
            ];

            if (isset($manifest['enabled']) && $manifest['enabled'] === true) {
                // Compile providers
                foreach ($manifest['providers'] ?? [] as $provider) {
                    $cache['providers'][] = $provider;
                }

                // Compile routes (scanning versioned paths and direct routes)
                $routesPath = $path . '/Presentation/Routes';
                if (is_dir($routesPath)) {
                    foreach (glob($routesPath . '/*.php') ?: [] as $routeFile) {
                        $cache['routes'][] = $routeFile;
                    }
                    $v1Path = $routesPath . '/v1';
                    if (is_dir($v1Path)) {
                        foreach (glob($v1Path . '/*.php') ?: [] as $routeFile) {
                            $cache['routes'][] = $routeFile;
                        }
                    }
                }

                // Compile permissions
                foreach ($manifest['permissions'] ?? [] as $permission) {
                    $cache['permissions'][] = $permission;
                }

                // Compile configurations
                $configDir = $path . '/Infrastructure/Config';
                if (is_dir($configDir)) {
                    foreach (glob($configDir . '/*.php') ?: [] as $configFile) {
                        $configKey = strtolower(basename($configFile, '.php'));
                        $cache['configs'][$configKey] = require $configFile;
                    }
                }
            }
        }

        $cachePath = base_path('bootstrap/cache/modules.php');
        $content = '<?php' . PHP_EOL . PHP_EOL . '// Generated by php artisan module:cache. Do not modify.' . PHP_EOL . 'return ' . var_export($cache, true) . ';' . PHP_EOL;

        file_put_contents($cachePath, $content);

        $this->info("Modules configuration cached successfully at [{$cachePath}].");

        return 0;
    }
}
